linters-settings:
  gocyclo:
    min-complexity: 50
  dupl:
    threshold: 5
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  revive:
    confidence: 0.8
  lll:
    line-length: 160
    # tab width in spaces. Default to 1.
    tab-width: 1
  funlen:
    lines: 150
    statements: 80

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - errcheck
    - funlen
    - goconst
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused

  # don't enable:
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - maligned
  # - prealloc

run:
  skip-dirs:
    # - test/testdata_etc
issues:
  exclude-rules:
  exclude-files:
    - ".*_test\\.go$"
