// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	goqueue "github.com/bxcodec/goqueue"
	mock "github.com/stretchr/testify/mock"
)

// InboundMessageHandler is an autogenerated mock type for the InboundMessageHandler type
type InboundMessageHandler struct {
	mock.Mock
}

// HandleMessage provides a mock function with given fields: ctx, m
func (_m *InboundMessageHandler) HandleMessage(ctx context.Context, m goqueue.InboundMessage) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, goqueue.InboundMessage) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInboundMessageHandler creates a new instance of InboundMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInboundMessageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *InboundMessageHandler {
	mock := &InboundMessageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
