// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	goqueue "github.com/bxcodec/goqueue"
	mock "github.com/stretchr/testify/mock"
)

// PublisherHandler is an autogenerated mock type for the PublisherHandler type
type PublisherHandler struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, m
func (_m *PublisherHandler) Publish(ctx context.Context, m goqueue.Message) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, goqueue.Message) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPublisherHandler creates a new instance of PublisherHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisherHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *PublisherHandler {
	mock := &PublisherHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
